[package]
name = "mkdmfs"
version = "0.1.0"
authors = ["Chris Williams <diodesign@tuta.io>"]
edition = "2018"

[dependencies]
dmfs = { path = "dmfs" }
clap = "3.0.0-beta.2"
toml = "0.5.7"
serde = "1.0.118"
serde_derive = "1.0.118"
regex = "1.4.2"